Created the SortKey dictionary node
mottmacdonaldglobal/Sandbox pull request #50
Opened 2022-02-10 02:28 UTC by WilliamHamiltonMM

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds the sort by key node to the dictionary project. 

## Related Tickets & Documents

Fixes #42 

## Added to documentation?

- [ ] 📜 readme
- [x] 📓 docs
- [ ] 🙅 no documentation needed

2022-02-10 04:17 UTC, sonomirco requested changes
Documentation is missed.

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Resources.resx
>      <value>resources\valuetypedicticon.png;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</value>
The naming convention of the file
GetTypeFromTheDictionaryValue 
Don't be afraid to be descriptive, try to be clear as possible.

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +
Remove empty lines.
All the below

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +                    foreach (var item in ghDict.Value.OrderBy(x => x.Key))
You could use
var sortedDict = ghDict.Value.OrderBy(x => x.Key).ToDictionary(x => x.Key, x => x.Value);
DA.SetData(0, sortedDict);

just 2 lines of code :)

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +                    this.Message = "Ascending";
just to be sure, move the message after you step into the case.

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +                    break;
Did you try removing the break, because maybe is not need it.

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +
Same comments as above

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +
remove empty lines

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +            //Otherwise actually set this._sortingMode to its new value
can you remove these comments?
Add comments if are useful to understand what you are doing, in this case, is very clear what you are doing.

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +
remove empty lines

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +
remove empty lines

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +                    // return the dictionary sorted in descending mode
remove is clear what is going on :)

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +                    // return the dictionary sorted in ascending mode
Remove is clear what is happening.

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +        //Create the _sortingMode property
remove, please.

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +        //Set description as well as assign default starting value to _sortingMode (Ascending)
remove, please.

2022-02-10 04:17 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +
remove empty line

2022-02-10 05:30 UTC, WilliamHamiltonMM commented on SandboxGh/Utility/SortKeyDictionary.cs
> +                    break;
case required a break at the end or it errors

2022-02-10 05:40 UTC, sonomirco commented on SandboxGh/Utility/SortKeyDictionary.cs
> +                    break;
Yep, I thought maybe the `Da` was able also to exit the switch :)

2022-02-11 01:04 UTC, sonomirco approved these changes

2022-02-11 01:04 UTC, merged